name: CI
 
on:
  pull_request:
    branches: [ main ]
 
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: decK ping
      id: decK_ping
      uses: ./
      with:
        command: "ping"
        #options: "--kong-addr ${{ secrets.KONG_ADDR }}" 
        options: "--konnect-addr https://konnect.konghq.com/ --konnect-email singhjaikrat@gmail.com --konnect-password Jaik@123"
    - name: decK validate
      id: decK_validate
      uses: ./
      with:
        command: "validate"
        options: "--konnect-addr https://konnect.konghq.com/ --konnect-email singhjaikrat@gmail.com --konnect-password Jaik@123"
        kong_workspaces: "default"
    - name: decK diff
      id: decK_diff
      uses: ./
      with:
        command: "diff"
        options: "--konnect-addr https://konnect.konghq.com/ --konnect-email singhjaikrat@gmail.com --konnect-password Jaik@123" 
        kong_workspaces: "default"